export type HapticType =
  | "selection"
  | "impactMedium"
  | "impactHeavy"
  | "notificationSuccess"
  | "notificationWarning"
  | "notificationError"
  | "clockTick"
  | "contextClick"
  | "keyboardPress"
  | "keyboardRelease"
  | "keyboardTap"
  | "longPress"
  | "textHandleMove"
  | "virtualKey"
  | "virtualKeyRelease";
